# Generated by Django 4.0.6 on 2022-10-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song'),
        ),
    ]